# ConfigMap for checkoutservice

apiVersion: v1
kind: ConfigMap
metadata:
  name: checkoutservice-config
  namespace: argocd  # Specify the namespace
data:
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  CART_SERVICE_ADDR: "cartservice:7070"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  EMAIL_SERVICE_ADDR: "emailservice:8080"
  PAYMENT_SERVICE_ADDR: "paymentservice:50051"
