# Deployment for the Checkout Service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: argocd  # Specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: kappu1512/checkoutservice:33
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: checkoutservice-config  # Use the ConfigMap
            - secretRef:
                name: checkoutservice-secrets  # Use the Secrets
