apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  type: ClusterIP  # Exposes the service only within the cluster
  selector:
    app: checkoutservice  # Matches the `app` label in the Deployment
  ports:
    - protocol: TCP
      port: 5050        # Port exposed on the Service (cluster-wide)
      targetPort: 5050  # Port on the container where the app is listening
