# ConfigMap for the frontend service

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: argocd  # Specify the namespace
data:
  GOTRACEBACK: "single"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8082"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  AD_SERVICE_ADDR: "adservice:9555"
  SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:XXXX"  # Replace XXXX with the actual port
