# Deployment for the frontend service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: argocd  # Specify the namespace
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kappu1512/frontend:26
          ports:
            - containerPort: 8080
          env:
            # Inject ConfigMap values as environment variables
            - name: GOTRACEBACK
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: GOTRACEBACK
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: PRODUCT_CATALOG_SERVICE_ADDR
            - name: CURRENCY_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: CURRENCY_SERVICE_ADDR
            - name: CART_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: CART_SERVICE_ADDR
            - name: RECOMMENDATION_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: RECOMMENDATION_SERVICE_ADDR
            - name: CHECKOUT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: CHECKOUT_SERVICE_ADDR
            - name: SHIPPING_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: SHIPPING_SERVICE_ADDR
            - name: AD_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: AD_SERVICE_ADDR
            - name: SHOPPING_ASSISTANT_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: SHOPPING_ASSISTANT_SERVICE_ADDR
            
            # Inject Secret values as environment variables
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: API_KEY
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: DATABASE_PASSWORD
