# This file contains the sensitive information that the frontend application needs to run.

apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: argocd  # Specify the namespace
type: Opaque
data:
  # Encode sensitive values using base64
  API_KEY: <base64_encoded_value>
  DATABASE_PASSWORD: <base64_encoded_password>
