apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  #type: LoadBalancer  # Use LoadBalancer if external access is needed
  type: NodePort      # Needed for Kubeadm setup 
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080        # Port on which this service will be accessible within the cluster
      targetPort: 8080  # Port on the pod where the container is listening