# loadgenerator Deployment and Service combined YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: kappu1512/loadgenerator:19
          env:
            - name: GEVENT_SUPPORT
              value: "True"