# This is a Deployment that runs a load generator container. It pulls configuration values from a ConfigMap and a Secret.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: argocd  # Specify the namespace
  labels:
    app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: kappu1512/loadgenerator:41
          env:
            # Pull values from ConfigMap
            - name: GEVENT_SUPPORT
              valueFrom:
                configMapKeyRef:
                  name: loadgenerator-config
                  key: GEVENT_SUPPORT

            # Pull sensitive values from Secret (if applicable)
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: loadgenerator-secrets
                  key: API_KEY
