# ConfigMap for the adservice application

apiVersion: v1
kind: ConfigMap
metadata:
  name: adservice-config
  namespace: argocd  # Specify the namespace
data:
  EXAMPLE_ENV: "example-value"
  OTHER_CONFIG: "some-other-value"
