# adservice Deployment YAML file 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: argocd  # Specify the namespace
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: kappu1512/adservice:33
          ports:
            - containerPort: 9555
          env:
            - name: EXAMPLE_ENV
              valueFrom:
                configMapKeyRef:
                  name: adservice-config
                  key: EXAMPLE_ENV
            - name: OTHER_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: adservice-config
                  key: OTHER_CONFIG
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: adservice-secrets
                  key: SECRET_KEY
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: adservice-secrets
                  key: API_TOKEN