# Secret YAML file for adservice

apiVersion: v1
kind: Secret
metadata:
  name: adservice-secrets
  namespace: argocd  # Specify the namespace
type: Opaque
data:
  SECRET_KEY: xxxxxxxx
  API_TOKEN: xxxxxxxx