apiVersion: v1
kind: Service
metadata:
  name: adservice
  labels:
    app: adservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: adservice
  ports:
    - protocol: TCP
      port: 9555        # Port on which this service will be accessible within the cluster
      targetPort: 9555  # Port on the pod where the container is listening