# currencyservice Deployment and Service combined YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: kappu1512/currencyservice:8
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"  # Define the gRPC server port
            - name: DISABLE_PROFILER
              value: "true"  # Disable Google Cloud Profiler