# Deployment file for the currencyservice application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: argocd  # Specify the namespace
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: kappu1512/currencyservice:34
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: currencyservice-config
                  key: PORT
            - name: DISABLE_PROFILER
              valueFrom:
                configMapKeyRef:
                  name: currencyservice-config
                  key: DISABLE_PROFILER
            - name: API_KEY  # Example of a secret
              valueFrom:
                secretKeyRef:
                  name: currencyservice-secrets
                  key: API_KEY
