# This file defines a Kubernetes service for the Currency Service

apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: argocd  # Specify the namespace
  labels:
    app: currencyservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: currencyservice
  ports:
    - protocol: TCP
      port: 7000        # Port on which this service will be accessible within the cluster
      targetPort: 7000  # Port on the pod where the container is listening