# This file contains the secrets for the productcatalogservice application.

apiVersion: v1
kind: Secret
metadata:
  name: productcatalog-secrets
  namespace: argocd  # Specify the namespace
type: Opaque
data:
  DATABASE_PASSWORD: xxxxxxxxx  # Base64-encoded value for "password"
