# cartservice Deployment YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: argocd  # Specify the namespace
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: kappu1512/cartservice:36
          ports:
            - containerPort: 7070
          env:
            - name: DOTNET_EnableDiagnostics
              valueFrom:
                configMapKeyRef:
                  name: cartservice-config
                  key: DOTNET_EnableDiagnostics
            - name: ASPNETCORE_HTTP_PORTS
              valueFrom:
                configMapKeyRef:
                  name: cartservice-config
                  key: ASPNETCORE_HTTP_PORTS
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: cartservice-secrets
                  key: REDIS_ADDR
