# This file defines a Kubernetes Service for the Cart Service

apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: argocd  # Specify the namespace
  labels:
    app: cartservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 7070         # Port on which this service will be accessible within the cluster
      targetPort: 7070   # Port on the pod where the container is listening