# paymentservice Deployment and Service combined YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: kappu1512/paymentservice:9
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"  # Define the gRPC server port
            - name: DISABLE_PROFILER
              value: "true"  # Disable Google Cloud Profiler