# Deployment for the paymentservice

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: kappu1512/paymentservice:42
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: PORT
            - name: DISABLE_PROFILER
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: DISABLE_PROFILER
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: paymentservice-secret
                  key: API_KEY
