# This file contains the secret key for the payment service

apiVersion: v1
kind: Secret
metadata:
  name: paymentservice-secret
  namespace: argocd  # Specify the namespace
type: Opaque
data:
  API_KEY: xxxxxxxxxxxxx  # Base64 encoded value of "secret_key"
