apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 50051        # Port on which this service will be accessible within the cluster
      targetPort: 50051  # Port on the pod where the container is listening