# This is the ConfigMap resource for the shippingservice application

apiVersion: v1
kind: ConfigMap
metadata:
  name: shippingservice-config
  namespace: argocd  # Specify the namespace
data:
  GOTRACEBACK: "single"  # This is the environment variable value
