# Deployment for the Shipping Service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: argocd  # Specify the namespace
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: kappu1512/shippingservice:45
          ports:
            - containerPort: 50051
          env:
            - name: GOTRACEBACK
              valueFrom:
                configMapKeyRef:
                  name: shippingservice-config  # Refers to the ConfigMap
                  key: GOTRACEBACK
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: shippingservice-secrets  # Refers to the Secret
                  key: API_KEY
