# This file defines a Kubernetes Service for the Shipping Service

apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: argocd  # Specify the namespace
  labels:
    app: shippingservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 50051        # Port on which this service will be accessible within the cluster
      targetPort: 50051  # Port on the pod where the container is listening