# emailservice Deployment YAML

apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: kappu1512/emailservice:40
          ports:
            - containerPort: 8080
          env:
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: emailservice-config
                  key: PYTHONUNBUFFERED
            - name: ENABLE_PROFILER
              valueFrom:
                configMapKeyRef:
                  name: emailservice-config
                  key: ENABLE_PROFILER
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: emailservice-secrets
                  key: API_KEY
