# This file contains the secret values for the emailservice application.

apiVersion: v1
kind: Secret
metadata:
  name: emailservice-secrets
type: Opaque
data:
  API_KEY: xxxxxxxxxxxx  # Base64-encoded value (e.g., "secret_key_value")
