# This file defines the service for the emailservice deployment

apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 8080        # Port on which this service will be accessible within the cluster
      targetPort: 8080  # Port on the pod where the container is listening