apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: kappu1512/recommendationservice:44
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: recommendationservice-config  # Reference to the ConfigMap
                  key: PORT
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              valueFrom:
                configMapKeyRef:
                  name: recommendationservice-config
                  key: PRODUCT_CATALOG_SERVICE_ADDR
            - name: DISABLE_PROFILER
              valueFrom:
                configMapKeyRef:
                  name: recommendationservice-config
                  key: DISABLE_PROFILER
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: recommendationservice-secrets  # Reference to the Secret
                  key: API_KEY
