apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  type: ClusterIP  # Internal service only, accessible within the cluster
  selector:
    app: recommendationservice
  ports:
    - protocol: TCP
      port: 8080        # Port on which this service will be accessible within the cluster
      targetPort: 8080  # Port on the pod where the container is listening